// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}
