// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function GetFile(arg1:string):Promise<main.ExcalidrawFile>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles():Promise<Array<main.ExcalidrawFile>>;

export function SaveFile(arg1:main.ExcalidrawFile):Promise<void>;
