name: Wails build

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'excaliapp'
            platform:  'linux/amd64'
            exesuffix: '-linux-amd64'
            os: 'ubuntu-latest'
          - name: 'excaliapp'
            platform:  'windows/amd64'
            exesuffix: '.exe'
            os: 'windows-2025'
          # - name: 'excaliapp'
          #   platform:  'darwin/universal'
          #   exesuffix: '-macos-amd64.app'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Setup Node Cache
        uses: actions/cache@v4
        with:
          key: ${{ github.job }}-${{ hashFiles('**/package-lock.json') }}
          path: node_modules
      
      - name: Setup OSSign
        uses: ossign/actions/setup-ossign@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install and build
        run: |
          npm i -g bun
          bun install
          bun run build:wails

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}${{ matrix.build.exesuffix }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          nsis: ${{ matrix.build.platform == 'windows/amd64' }}
          go-version: '1.24.2'
      
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        # Only of not a tag
        if: startsWith(github.ref, 'refs/heads/')
        with:
          name: ${{ matrix.build.os }}-artifacts
          path: build/bin/
      
      - name: Build fully signed NSIS installer
        if: matrix.build.platform == 'windows/amd64' && startsWith(github.ref, 'refs/tags/')
        env:
          OSSIGN_CONFIG: ${{ secrets.OSSIGN_CONFIG }}
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest https://deac-riga.dl.sourceforge.net/project/nsis/NSIS%203/3.10/nsis-3.10-setup.exe?viasf=1 -OutFile .\nsis-3.10-setup.exe
          $process = Start-Process ".\nsis-3.10-setup.exe" -ArgumentList "/S" -Wait -PassThru
          $exitCode = $process.ExitCode
          if ($exitCode -eq 0) {
              Write-Host "Installer ran successfully."
          } else {
              Write-Host "Installer failed with exit code $exitCode."
              exit $exitCode
          }

          echo "C:\Program Files (x86)\NSIS\Bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath "$env:GITHUB_PATH" -Append

          $env:PATH += ";C:\Program Files (x86)\NSIS\Bin;C:\Program Files (x86)\NSIS"
          Write-Host "PATH updated to include NSIS."
          ls "C:\Program Files (x86)\NSIS\"
          ls "C:\Program Files (x86)\NSIS\Bin\"

          rm .\build\bin\*installer.exe

          ossign.exe build\bin\excaliapp.exe

          makensis.exe "-DARG_WAILS_AMD64_BINARY=..\..\bin\excaliapp.exe" ".\build\windows\installer\project.nsi"          
      

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/bin/*
          tag_name: ${{ github.ref_name }}
          name: Version ${{ github.ref_name }}
          body: |
            ## Excaliapp Desktop Release
            This release includes the latest desktop build of Excaliapp